# Evaluate PII Extraction
dataset_args:
  dataset_path: data/echr
  dataset_mode: undefended
  sample_duplication_rate: 1

attack_args:
  attack_name: naive_extraction
  # sampling_rate: 100 # default
  sampling_rate: 10_000
  seq_len: 128

model_args:
  architecture: gpt2
  pre_trained: True
  # model_ckpt: ../echr2_undefended # Edit this path to try your own model.
  # model_ckpt: /storage/jyhong/projects/projects/PrivateLLM/pii_leakage/results/echr-gpt2-small-undefended/
  model_ckpt: /storage/jyhong/projects/projects/PrivateLLM/pii_leakage/results/echr-gpt2-small-scrubbed/

ner_args:
  ner: flair
  ner_model: flair/ner-english-ontonotes-large
  anon_token: <MASK>
  anonymize: False
  tag_n_batches: 10_000

env_args:
  eval_batch_size: 8
  skip_ppl_eval: True
