# Evaluate PII Extraction
dataset_args:
  dataset_path: data/echr
  dataset_mode: undefended
  sample_duplication_rate: 1

attack_args:
  attack_name: naive_extraction
  # sampling_rate: 100 # default
  sampling_rate: 10_000
  seq_len: 128

privacy_args:
  target_epsilon: 8

model_args:
  architecture: meta-llama/Llama-2-7b-hf
  pre_trained: True   # Start from a pre-trained checkpoint
  # peft
  peft: lora
  model_ckpt: results/echr-llama2-7b-dp8/

ner_args:
  ner: flair
  ner_model: flair/ner-english-ontonotes-large
  anon_token: <MASK>
  anonymize: False
  tag_n_batches: 10_000

env_args:
  eval_batch_size: 16
  skip_ppl_eval: True
