# Fine-tune an LM on the enron text dataset.

dataset_args:
  # dataset_path: ../src/pii_leakage/extern/echr
  dataset_path: data/enron
  dataset_mode: undefended
  sample_duplication_rate: 1
  pseudonymize: False

trainer_args:
  output_dir: ./results/enron-llama2-7b-chat-dp8/
  # evaluation_strategy: steps
  # eval_steps: 200
  logging_steps: 10
  save_total_limit: 2
  save_strategy: steps
  save_steps: 100
  overwrite_output_dir: True
  # save_steps: 750  # forgot to remove
  callback_after_n_steps: 100
  num_train_epochs: 4
  # batch size=32
  gradient_accumulation_steps: 16
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 1
  remove_unused_columns: False
  learning_rate: 0.00001
  resume_from_checkpoint: True

privacy_args:
  target_epsilon: 8

model_args:
  architecture: meta-llama/Llama-2-7b-chat-hf
  pre_trained: True   # Start from a pre-trained checkpoint
  # peft
  peft: lora

ner_args:
  ner: flair
  ner_model: flair/ner-english-ontonotes-large
  anon_token: <MASK>
  anonymize: False
